import {initializeApp} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {getAuth,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,getDoc,addDoc,query,where,orderBy,limit,getAggregateFromServer,average,count} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyChYh6bHiB7dAAcDYbrHzW61gyQR0A5UuM",authDomain:"ninjaturtels.firebaseapp.com",projectId:"ninjaturtels",storageBucket:"ninjaturtels.firebasestorage.app",messagingSenderId:"1063186224531",appId:"1:1063186224531:web:76b1369b477808e4654466",measurementId:"G-HEB32CJR1N"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),CL=Array.from({length:10},(_,i)=>`1/${i+1}`);let me,students=[],stats=[],schoolAvg=0;const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
onAuthStateChanged(auth,async u=>{if(!u){location.href='login.html';return;}const s=await getDoc(doc(db,'users',u.uid));if(!s.exists()||s.data().role!=='principal'){alert('ليس لديك صلاحية الوصول');await signOut(auth);location.href='login.html';return;}me={uid:u.uid,...s.data()};document.getElementById('principalName').textContent=me.name||'المديرة';load();});
async function load(){const [us,topSnap,aggSnap]=await Promise.all([getDocs(query(collection(db,'users'),where('role','==','student'))),getDocs(query(collection(db,'studentStats'),orderBy('totalXP','desc'),limit(10))),getAggregateFromServer(collection(db,'studentStats'),{avg:average('avgScore'),total:count()})]);students=us.docs.map(d=>({id:d.id,...d.data()}));stats=topSnap.docs.map(d=>({id:d.id,...d.data()}));schoolAvg=Math.round(aggSnap.data().avg||0);render();}
function render(){const avg=schoolAvg;const flags=students.filter(x=>x.redFlag).length;document.getElementById('schoolStats').innerHTML=`<div class="stat"><span>إجمالي الطلاب</span><b>${students.length}</b></div><div class="stat"><span>المدرسين</span><b id="teacherCount">—</b></div><div class="stat"><span>Red Flag</span><b>${flags}</b></div><div class="stat"><span>متوسط المدرسة</span><b>${avg}%</b></div>`;loadTeacherCount();const counts=Object.fromEntries(CL.map(c=>[c,0]));students.forEach(s=>{if(counts[s.class]!=null)counts[s.class]++});document.getElementById('classesGrid').innerHTML=CL.map(c=>`<div class="class-card"><span>${c}</span><b>${counts[c]}</b><small>طالب</small></div>`).join('');document.getElementById('flaggedStudents').innerHTML=students.filter(x=>x.redFlag).map(s=>`<div class="list-row"><div><strong>${esc(s.name)}</strong><small>الفصل ${esc(s.class)}</small></div><span class="flag">🚩 Red Flag</span></div>`).join('')||'<p class="empty">لا يوجد طلاب عليهم Red Flag.</p>';document.getElementById('topStudents').innerHTML=stats.map((s,i)=>`<div class="list-row"><div><strong>${i+1}. ${esc(s.studentName||'طالب')}</strong><small>الفصل ${esc(s.class||'—')} • ${s.completedQuizzes||0} كويز</small></div><b>${s.totalXP||0} XP</b></div>`).join('')||'<p class="empty">لا توجد نتائج بعد.</p>';}
async function loadTeacherCount(){const s=await getDocs(query(collection(db,'users'),where('role','==','teacher')));document.getElementById('teacherCount').textContent=s.size;}
document.getElementById('logoutBtn').onclick=()=>signOut(auth).then(()=>location.href='login.html');document.getElementById('openAnnouncement').onclick=()=>document.getElementById('announcementModal').classList.remove('hidden');['closeAnnouncement','cancelAnnouncement'].forEach(id=>document.getElementById(id).onclick=()=>document.getElementById('announcementModal').classList.add('hidden'));document.getElementById('announcementForm').onsubmit=async e=>{e.preventDefault();const title=document.getElementById('announcementTitle').value.trim(),content=document.getElementById('announcementContent').value.trim();try{await addDoc(collection(db,'announcements'),{title,content,principalId:me.uid,principalName:me.name||'',teacherId:'',teacherName:'',subject:'إدارة المدرسة',targetClasses:CL,targetClass:CL[0],schoolWide:true,createdAt:new Date().toISOString(),readBy:[]});alert('تم إرسال الإشعار إلى المدرسة بالكامل');document.getElementById('announcementModal').classList.add('hidden');e.target.reset();}catch(err){alert('حدث خطأ: '+err.message);}};
